/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Isla.glb --types 
*/

import * as THREE from "three"
type GLTFAction = THREE.AnimationClip
import { useGLTF } from "@react-three/drei"
import type { GLTF } from "three-stdlib"
import type { ThreeElements } from "@react-three/fiber"

type GLTFResult = GLTF & {
  nodes: {
    Isla: THREE.Mesh
    Agua: THREE.Mesh
    Roca_1: THREE.Mesh
    Roca_2: THREE.Mesh
    Roca_3: THREE.Mesh
    Arbol: THREE.Mesh
    Arbol002: THREE.Mesh
    piedra1013: THREE.Mesh
    Plane044: THREE.Mesh
    piedra1024: THREE.Mesh
    Plane045: THREE.Mesh
    Plane046: THREE.Mesh
    Plane047: THREE.Mesh
    Plane048: THREE.Mesh
    Plane049: THREE.Mesh
    piedra1025: THREE.Mesh
    Plane050: THREE.Mesh
    piedra1026: THREE.Mesh
    Plane051: THREE.Mesh
    Plane052: THREE.Mesh
    piedra1027: THREE.Mesh
    Plane053: THREE.Mesh
    Plane054: THREE.Mesh
    piedra1028: THREE.Mesh
    Plane055: THREE.Mesh
    piedra1029: THREE.Mesh
    piedra1030: THREE.Mesh
    Plane056: THREE.Mesh
    Plane057: THREE.Mesh
    piedra1031: THREE.Mesh
    piedra1032: THREE.Mesh
    Plane058: THREE.Mesh
    Plane059: THREE.Mesh
    Plane060: THREE.Mesh
    Plane061: THREE.Mesh
    piedra1033: THREE.Mesh
    Plane062: THREE.Mesh
    piedra1034: THREE.Mesh
    Plane063: THREE.Mesh
    Plane064: THREE.Mesh
    Plane065: THREE.Mesh
    Plane066: THREE.Mesh
    Plane067: THREE.Mesh
    piedra1035: THREE.Mesh
    Plane068: THREE.Mesh
    piedra1036: THREE.Mesh
    Plane069: THREE.Mesh
    Plane070: THREE.Mesh
    piedra1037: THREE.Mesh
    Plane071: THREE.Mesh
    Plane072: THREE.Mesh
    piedra1038: THREE.Mesh
    Plane073: THREE.Mesh
    piedra1039: THREE.Mesh
    piedra1040: THREE.Mesh
    Plane074: THREE.Mesh
    Plane075: THREE.Mesh
    piedra1041: THREE.Mesh
    piedra1042: THREE.Mesh
    Plane076: THREE.Mesh
    Plane077: THREE.Mesh
    Plane078: THREE.Mesh
    Plane079: THREE.Mesh
    piedra1043: THREE.Mesh
    Plane080: THREE.Mesh
    piedra1044: THREE.Mesh
    Plane081: THREE.Mesh
    Plane082: THREE.Mesh
    Plane083: THREE.Mesh
    Plane084: THREE.Mesh
    Plane085: THREE.Mesh
    piedra1045: THREE.Mesh
    Plane086: THREE.Mesh
    piedra1046: THREE.Mesh
    Plane087: THREE.Mesh
    Plane088: THREE.Mesh
    piedra1047: THREE.Mesh
    Plane089: THREE.Mesh
    Plane090: THREE.Mesh
    piedra1048: THREE.Mesh
    Plane091: THREE.Mesh
    piedra1049: THREE.Mesh
    piedra1050: THREE.Mesh
    Plane092: THREE.Mesh
    Plane093: THREE.Mesh
    piedra1051: THREE.Mesh
    piedra1052: THREE.Mesh
    Plane094: THREE.Mesh
    Plane095: THREE.Mesh
    Plane096: THREE.Mesh
    Plane097: THREE.Mesh
    Cube001: THREE.Mesh
    Cube024: THREE.Mesh
    Cube026: THREE.Mesh
    Cube027: THREE.Mesh
    Cube028: THREE.Mesh
    Cube029: THREE.Mesh
    Cube030: THREE.Mesh
    Cube031: THREE.Mesh
    Cube032: THREE.Mesh
    Cube033: THREE.Mesh
    Cube034: THREE.Mesh
    Cube035: THREE.Mesh
    Cube036: THREE.Mesh
    Cube037: THREE.Mesh
    Cube041: THREE.Mesh
    Cube042: THREE.Mesh
    Cube043: THREE.Mesh
    Cube044: THREE.Mesh
    piedra1001: THREE.Mesh
    Plane001: THREE.Mesh
    piedra1003: THREE.Mesh
    Plane003: THREE.Mesh
    Plane006: THREE.Mesh
    Plane007: THREE.Mesh
    Plane008: THREE.Mesh
    Plane009: THREE.Mesh
    piedra1004: THREE.Mesh
    Plane010: THREE.Mesh
    piedra1005: THREE.Mesh
    Plane011: THREE.Mesh
    Plane012: THREE.Mesh
    piedra1006: THREE.Mesh
    Plane013: THREE.Mesh
    Plane014: THREE.Mesh
    piedra1007: THREE.Mesh
    Plane015: THREE.Mesh
    piedra1008: THREE.Mesh
    piedra1009: THREE.Mesh
    Plane016: THREE.Mesh
    Plane017: THREE.Mesh
    piedra1010: THREE.Mesh
    piedra1011: THREE.Mesh
    Plane018: THREE.Mesh
    Plane019: THREE.Mesh
    Plane020: THREE.Mesh
    Plane021: THREE.Mesh
    piedra1012: THREE.Mesh
    Plane022: THREE.Mesh
    piedra1015: THREE.Mesh
    Plane023: THREE.Mesh
    Plane025: THREE.Mesh
    Plane028: THREE.Mesh
    Plane029: THREE.Mesh
    Plane030: THREE.Mesh
    piedra1016: THREE.Mesh
    Plane031: THREE.Mesh
    piedra1017: THREE.Mesh
    Plane032: THREE.Mesh
    Plane033: THREE.Mesh
    piedra1018: THREE.Mesh
    Plane034: THREE.Mesh
    Plane035: THREE.Mesh
    piedra1019: THREE.Mesh
    Plane036: THREE.Mesh
    piedra1020: THREE.Mesh
    piedra1021: THREE.Mesh
    Plane037: THREE.Mesh
    Plane038: THREE.Mesh
    piedra1022: THREE.Mesh
    piedra1023: THREE.Mesh
    Plane039: THREE.Mesh
    Plane040: THREE.Mesh
    Plane041: THREE.Mesh
    Plane042: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    Cube011: THREE.Mesh
    Cube012: THREE.Mesh
    Cube013: THREE.Mesh
    Cube014: THREE.Mesh
    Cube015: THREE.Mesh
    Cube016: THREE.Mesh
    Cube017: THREE.Mesh
    Cube018: THREE.Mesh
    Cube019: THREE.Mesh
    Cube020: THREE.Mesh
    Cube045: THREE.Mesh
    Cube046: THREE.Mesh
    Cube047: THREE.Mesh
    Cube048: THREE.Mesh
    Cube049: THREE.Mesh
    Cube050: THREE.Mesh
    Cube051: THREE.Mesh
    piedra1053: THREE.Mesh
    piedra1055: THREE.Mesh
    piedra1054: THREE.Mesh
    Plane043: THREE.Mesh
    Cube052: THREE.Mesh
    Cube053: THREE.Mesh
    Cube054: THREE.Mesh
    Cube055: THREE.Mesh
    Cube056: THREE.Mesh
    Cube057: THREE.Mesh
    Cube058: THREE.Mesh
    Cube059: THREE.Mesh
    Cube060: THREE.Mesh
    Cube061: THREE.Mesh
    Cube062: THREE.Mesh
    Cube063: THREE.Mesh
    Cube064: THREE.Mesh
    Cube065: THREE.Mesh
    Plane099: THREE.Mesh
    Cube007: THREE.Mesh
    Cube021: THREE.Mesh
    Cube: THREE.Mesh
    Cube022: THREE.Mesh
    Cube023: THREE.Mesh
    Cube025: THREE.Mesh
    Cube038: THREE.Mesh
    Cube039: THREE.Mesh
    Cube040: THREE.Mesh
    Cube066: THREE.Mesh
    Cube067: THREE.Mesh
    Cube068: THREE.Mesh
    Cube069: THREE.Mesh
    Cube070: THREE.Mesh
    Cube071: THREE.Mesh
    Cube072: THREE.Mesh
    Cube074: THREE.Mesh
    Cube075: THREE.Mesh
    Cube076: THREE.Mesh
    Cube077: THREE.Mesh
    Cube079: THREE.Mesh
    Cube080: THREE.Mesh
    Cube081: THREE.Mesh
    Cube073: THREE.Mesh
    Cube078: THREE.Mesh
    Cube082: THREE.Mesh
    Cube083: THREE.Mesh
    Cube084: THREE.Mesh
    Cube085: THREE.Mesh
    Cube086: THREE.Mesh
    Cube087: THREE.Mesh
    Cube088: THREE.Mesh
    Cube089: THREE.Mesh
    Cube090: THREE.Mesh
    Cube091: THREE.Mesh
    Cube092: THREE.Mesh
    Cube093: THREE.Mesh
    Cube094: THREE.Mesh
    Cube095: THREE.Mesh
    Cube096: THREE.Mesh
    Cube097: THREE.Mesh
    Cube098: THREE.Mesh
    Cube099: THREE.Mesh
    Cube100: THREE.Mesh
    Cube101: THREE.Mesh
    Cube102: THREE.Mesh
    Cube103: THREE.Mesh
    Cube104: THREE.Mesh
    Cube105: THREE.Mesh
    Cube106: THREE.Mesh
    Icosphere: THREE.Mesh
    Icosphere003: THREE.Mesh
    Icosphere001: THREE.Mesh
    Cube107: THREE.Mesh
    Sphere: THREE.Mesh
    Cone: THREE.Mesh
    Cone001: THREE.Mesh
    Sphere001: THREE.Mesh
    Sphere002: THREE.Mesh
    Sphere003: THREE.Mesh
    Sphere004: THREE.Mesh
    Sphere005: THREE.Mesh
    Icosphere002: THREE.Mesh
    Icosphere004: THREE.Mesh
    Icosphere005: THREE.Mesh
    Cube108: THREE.Mesh
    Cube109: THREE.Mesh
    Cube110: THREE.Mesh
    Cube111: THREE.Mesh
    Cube112: THREE.Mesh
    Cube113: THREE.Mesh
    Cube114: THREE.Mesh
    Cube115: THREE.Mesh
    Cube116: THREE.Mesh
    Sphere006: THREE.Mesh
    Sphere007: THREE.Mesh
    Sphere008: THREE.Mesh
    Sphere009: THREE.Mesh
    Sphere010: THREE.Mesh
    Sphere011: THREE.Mesh
    Sphere012: THREE.Mesh
    Sphere013: THREE.Mesh
    Sphere014: THREE.Mesh
    Sphere015: THREE.Mesh
    Cube117: THREE.Mesh
    Cube118: THREE.Mesh
    Cube119: THREE.Mesh
    Cube120: THREE.Mesh
    NurbsCurve: THREE.Mesh
    Arbol003: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Isla(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF("/Isla.glb") as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Isla.geometry} material={materials.Material} />
      <mesh
        geometry={nodes.Agua.geometry}
        material={materials.Material}
        position={[9.859, 0.283, -0.003]}
      />
      <mesh
        geometry={nodes.Roca_1.geometry}
        material={materials.Material}
        position={[9.132, 0.633, -1.666]}
      />
      <mesh
        geometry={nodes.Roca_2.geometry}
        material={materials.Material}
        position={[9.126, 0.616, 1.495]}
        rotation={[0.146, 0.109, -0.06]}
        scale={1.48}
      />
      <mesh
        geometry={nodes.Roca_3.geometry}
        material={materials.Material}
        position={[8.532, 0.552, -0.287]}
        rotation={[2.944, 0.744, -3.051]}
        scale={1.714}
      />
      <mesh
        geometry={nodes.Arbol.geometry}
        material={materials.Material}
        position={[0, 3.027, 0]}
        rotation={[0.082, -0.188, 0.015]}
        scale={[0.778, 0.426, 0.778]}
      />
      <mesh
        geometry={nodes.Arbol002.geometry}
        material={materials.Material}
        position={[-0.6, 3.027, -7.544]}
        rotation={[0.082, -0.188, 0.015]}
        scale={[0.778, 0.426, 0.778]}
      />
      <mesh
        geometry={nodes.piedra1013.geometry}
        material={materials.Material}
        position={[-6.335, -0.005, -0.542]}
      />
      <mesh
        geometry={nodes.Plane044.geometry}
        material={materials.Material}
        position={[-6.217, 1.195, -0.52]}
      />
      <mesh
        geometry={nodes.piedra1024.geometry}
        material={materials.Material}
        position={[-6.219, 1.041, -0.524]}
      />
      <mesh
        geometry={nodes.Plane045.geometry}
        material={materials.Material}
        position={[-6.274, 0.428, -0.465]}
      />
      <mesh
        geometry={nodes.Plane046.geometry}
        material={materials.Material}
        position={[-6.215, 1.295, -0.513]}
      />
      <mesh
        geometry={nodes.Plane047.geometry}
        material={materials.Material}
        position={[-6.252, 0.649, -0.474]}
      />
      <mesh
        geometry={nodes.Plane048.geometry}
        material={materials.Material}
        position={[-6.249, 0.863, -0.477]}
      />
      <mesh
        geometry={nodes.Plane049.geometry}
        material={materials.Material}
        position={[-6.215, 1.542, -0.552]}
      />
      <mesh
        geometry={nodes.piedra1025.geometry}
        material={materials.Material}
        position={[-6.231, 1.626, -0.514]}
      />
      <mesh
        geometry={nodes.Plane050.geometry}
        material={materials.Material}
        position={[-6.29, 1.772, -0.498]}
      />
      <mesh
        geometry={nodes.piedra1026.geometry}
        material={materials.Material}
        position={[-6.289, 1.989, -0.47]}
      />
      <mesh
        geometry={nodes.Plane051.geometry}
        material={materials.Material}
        position={[-6.336, 2.144, -0.586]}
      />
      <mesh
        geometry={nodes.Plane052.geometry}
        material={materials.Material}
        position={[-6.269, 2.359, -0.515]}
      />
      <mesh
        geometry={nodes.piedra1027.geometry}
        material={materials.Material}
        position={[-6.305, 2.777, -0.545]}
      />
      <mesh
        geometry={nodes.Plane053.geometry}
        material={materials.Material}
        position={[-6.297, 2.571, -0.499]}
      />
      <mesh
        geometry={nodes.Plane054.geometry}
        material={materials.Material}
        position={[-6.293, 2.941, -0.464]}
      />
      <mesh
        geometry={nodes.piedra1028.geometry}
        material={materials.Material}
        position={[-6.292, 3.148, -0.497]}
      />
      <mesh
        geometry={nodes.Plane055.geometry}
        material={materials.Material}
        position={[-6.335, 3.305, -0.447]}
      />
      <mesh
        geometry={nodes.piedra1029.geometry}
        material={materials.Material}
        position={[-6.326, 3.481, -0.452]}
      />
      <mesh
        geometry={nodes.piedra1030.geometry}
        material={materials.Material}
        position={[-6.448, 3.621, -0.4]}
      />
      <mesh
        geometry={nodes.Plane056.geometry}
        material={materials.Material}
        position={[-6.369, 4.148, -0.422]}
      />
      <mesh
        geometry={nodes.Plane057.geometry}
        material={materials.Material}
        position={[-6.417, 3.755, -0.404]}
      />
      <mesh
        geometry={nodes.piedra1031.geometry}
        material={materials.Material}
        position={[-6.407, 3.979, -0.384]}
      />
      <mesh
        geometry={nodes.piedra1032.geometry}
        material={materials.Material}
        position={[-6.506, 4.536, -0.448]}
      />
      <mesh
        geometry={nodes.Plane058.geometry}
        material={materials.Material}
        position={[-6.433, 4.346, -0.52]}
      />
      <mesh
        geometry={nodes.Plane059.geometry}
        material={materials.Material}
        position={[-6.546, 4.7, -0.46]}
      />
      <mesh
        geometry={nodes.Plane060.geometry}
        material={materials.Material}
        position={[-6.542, 4.85, -0.427]}
      />
      <mesh
        geometry={nodes.Plane061.geometry}
        material={materials.Material}
        position={[-6.511, 4.958, -0.419]}
      />
      <mesh
        geometry={nodes.piedra1033.geometry}
        material={materials.Material}
        position={[-6.296, 0.165, -3.279]}
      />
      <mesh
        geometry={nodes.Plane062.geometry}
        material={materials.Material}
        position={[-6.209, 1.264, -3.336]}
      />
      <mesh
        geometry={nodes.piedra1034.geometry}
        material={materials.Material}
        position={[-6.211, 1.11, -3.34]}
      />
      <mesh
        geometry={nodes.Plane063.geometry}
        material={materials.Material}
        position={[-6.266, 0.497, -3.281]}
      />
      <mesh
        geometry={nodes.Plane064.geometry}
        material={materials.Material}
        position={[-6.207, 1.364, -3.329]}
      />
      <mesh
        geometry={nodes.Plane065.geometry}
        material={materials.Material}
        position={[-6.244, 0.718, -3.29]}
      />
      <mesh
        geometry={nodes.Plane066.geometry}
        material={materials.Material}
        position={[-6.241, 0.932, -3.293]}
      />
      <mesh
        geometry={nodes.Plane067.geometry}
        material={materials.Material}
        position={[-6.207, 1.611, -3.368]}
      />
      <mesh
        geometry={nodes.piedra1035.geometry}
        material={materials.Material}
        position={[-6.223, 1.695, -3.33]}
      />
      <mesh
        geometry={nodes.Plane068.geometry}
        material={materials.Material}
        position={[-6.282, 1.841, -3.313]}
      />
      <mesh
        geometry={nodes.piedra1036.geometry}
        material={materials.Material}
        position={[-6.281, 2.058, -3.286]}
      />
      <mesh
        geometry={nodes.Plane069.geometry}
        material={materials.Material}
        position={[-6.328, 2.213, -3.402]}
      />
      <mesh
        geometry={nodes.Plane070.geometry}
        material={materials.Material}
        position={[-6.261, 2.428, -3.331]}
      />
      <mesh
        geometry={nodes.piedra1037.geometry}
        material={materials.Material}
        position={[-6.297, 2.845, -3.361]}
      />
      <mesh
        geometry={nodes.Plane071.geometry}
        material={materials.Material}
        position={[-6.289, 2.64, -3.315]}
      />
      <mesh
        geometry={nodes.Plane072.geometry}
        material={materials.Material}
        position={[-6.286, 3.01, -3.28]}
      />
      <mesh
        geometry={nodes.piedra1038.geometry}
        material={materials.Material}
        position={[-6.284, 3.217, -3.313]}
      />
      <mesh
        geometry={nodes.Plane073.geometry}
        material={materials.Material}
        position={[-6.327, 3.373, -3.262]}
      />
      <mesh
        geometry={nodes.piedra1039.geometry}
        material={materials.Material}
        position={[-6.318, 3.55, -3.268]}
      />
      <mesh
        geometry={nodes.piedra1040.geometry}
        material={materials.Material}
        position={[-6.44, 3.69, -3.216]}
      />
      <mesh
        geometry={nodes.Plane074.geometry}
        material={materials.Material}
        position={[-6.361, 4.217, -3.237]}
      />
      <mesh
        geometry={nodes.Plane075.geometry}
        material={materials.Material}
        position={[-6.409, 3.824, -3.22]}
      />
      <mesh
        geometry={nodes.piedra1041.geometry}
        material={materials.Material}
        position={[-6.399, 4.048, -3.2]}
      />
      <mesh
        geometry={nodes.piedra1042.geometry}
        material={materials.Material}
        position={[-6.498, 4.605, -3.264]}
      />
      <mesh
        geometry={nodes.Plane076.geometry}
        material={materials.Material}
        position={[-6.425, 4.415, -3.215]}
      />
      <mesh
        geometry={nodes.Plane077.geometry}
        material={materials.Material}
        position={[-6.538, 4.769, -3.276]}
      />
      <mesh
        geometry={nodes.Plane078.geometry}
        material={materials.Material}
        position={[-6.534, 4.919, -3.243]}
      />
      <mesh
        geometry={nodes.Plane079.geometry}
        material={materials.Material}
        position={[-6.57, 5.027, -3.235]}
      />
      <mesh
        geometry={nodes.piedra1043.geometry}
        material={materials.Material}
        position={[-6.23, 0.326, -6.097]}
      />
      <mesh
        geometry={nodes.Plane080.geometry}
        material={materials.Material}
        position={[-6.143, 1.426, -6.154]}
      />
      <mesh
        geometry={nodes.piedra1044.geometry}
        material={materials.Material}
        position={[-6.146, 1.271, -6.158]}
      />
      <mesh
        geometry={nodes.Plane081.geometry}
        material={materials.Material}
        position={[-6.201, 0.659, -6.099]}
      />
      <mesh
        geometry={nodes.Plane082.geometry}
        material={materials.Material}
        position={[-6.141, 1.525, -6.147]}
      />
      <mesh
        geometry={nodes.Plane083.geometry}
        material={materials.Material}
        position={[-6.179, 0.879, -6.108]}
      />
      <mesh
        geometry={nodes.Plane084.geometry}
        material={materials.Material}
        position={[-6.175, 1.093, -6.111]}
      />
      <mesh
        geometry={nodes.Plane085.geometry}
        material={materials.Material}
        position={[-6.142, 1.772, -6.186]}
      />
      <mesh
        geometry={nodes.piedra1045.geometry}
        material={materials.Material}
        position={[-6.158, 1.856, -6.148]}
      />
      <mesh
        geometry={nodes.Plane086.geometry}
        material={materials.Material}
        position={[-6.217, 2.002, -6.132]}
      />
      <mesh
        geometry={nodes.piedra1046.geometry}
        material={materials.Material}
        position={[-6.216, 2.22, -6.104]}
      />
      <mesh
        geometry={nodes.Plane087.geometry}
        material={materials.Material}
        position={[-6.263, 2.374, -6.22]}
      />
      <mesh
        geometry={nodes.Plane088.geometry}
        material={materials.Material}
        position={[-6.196, 2.589, -6.149]}
      />
      <mesh
        geometry={nodes.piedra1047.geometry}
        material={materials.Material}
        position={[-6.232, 3.007, -6.179]}
      />
      <mesh
        geometry={nodes.Plane089.geometry}
        material={materials.Material}
        position={[-6.223, 2.801, -6.133]}
      />
      <mesh
        geometry={nodes.Plane090.geometry}
        material={materials.Material}
        position={[-6.22, 3.171, -6.098]}
      />
      <mesh
        geometry={nodes.piedra1048.geometry}
        material={materials.Material}
        position={[-6.218, 3.378, -6.131]}
      />
      <mesh
        geometry={nodes.Plane091.geometry}
        material={materials.Material}
        position={[-6.261, 3.535, -6.081]}
      />
      <mesh
        geometry={nodes.piedra1049.geometry}
        material={materials.Material}
        position={[-6.253, 3.711, -6.087]}
      />
      <mesh
        geometry={nodes.piedra1050.geometry}
        material={materials.Material}
        position={[-6.375, 3.851, -6.034]}
      />
      <mesh
        geometry={nodes.Plane092.geometry}
        material={materials.Material}
        position={[-6.296, 4.378, -6.189]}
      />
      <mesh
        geometry={nodes.Plane093.geometry}
        material={materials.Material}
        position={[-6.343, 3.985, -6.201]}
      />
      <mesh
        geometry={nodes.piedra1051.geometry}
        material={materials.Material}
        position={[-6.333, 4.209, -6.188]}
      />
      <mesh
        geometry={nodes.piedra1052.geometry}
        material={materials.Material}
        position={[-6.433, 4.766, -6.15]}
      />
      <mesh
        geometry={nodes.Plane094.geometry}
        material={materials.Material}
        position={[-6.36, 4.576, -6.271]}
      />
      <mesh
        geometry={nodes.Plane095.geometry}
        material={materials.Material}
        position={[-6.472, 4.93, -6.094]}
      />
      <mesh
        geometry={nodes.Plane096.geometry}
        material={materials.Material}
        position={[-6.469, 5.081, -6.061]}
      />
      <mesh
        geometry={nodes.Plane097.geometry}
        material={materials.Material}
        position={[-6.438, 5.188, -6.053]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials.Material}
        position={[-6.471, 6.277, -3.886]}
        rotation={[-1.006, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials.Material}
        position={[-6.488, 6.378, -4.09]}
        rotation={[-1.134, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={materials.Material}
        position={[-6.463, 6.443, -4.291]}
        rotation={[-1.307, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={materials.Material}
        position={[-6.479, 6.481, -4.484]}
        rotation={[-1.53, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={materials.Material}
        position={[-6.482, 6.451, -4.734]}
        rotation={[-1.654, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube030.geometry}
        material={materials.Material}
        position={[-6.455, 6.384, -4.955]}
        rotation={[-1.827, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube031.geometry}
        material={materials.Material}
        position={[-6.45, 6.331, -5.149]}
        rotation={[-1.902, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube032.geometry}
        material={materials.Material}
        position={[-6.423, 6.247, -5.383]}
        rotation={[-2.017, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube033.geometry}
        material={materials.Material}
        position={[-6.43, 6.12, -5.583]}
        rotation={[-2.152, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube034.geometry}
        material={materials.Material}
        position={[-6.462, 6.001, -5.773]}
        rotation={[-2.307, -0.008, -0.228]}
      />
      <mesh
        geometry={nodes.Cube035.geometry}
        material={materials.Material}
        position={[-6.441, 5.854, -5.943]}
        rotation={[-2.461, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube036.geometry}
        material={materials.Material}
        position={[-6.382, 5.64, -6.053]}
        rotation={[-2.585, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube037.geometry}
        material={materials.Material}
        position={[-6.399, 5.532, -6.082]}
        rotation={[-2.688, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube041.geometry}
        material={materials.Material}
        position={[-6.403, 5.444, -6.303]}
        scale={0.901}
      />
      <mesh
        geometry={nodes.Cube042.geometry}
        material={materials.Material}
        position={[-6.346, 5.427, -6.038]}
        scale={0.901}
      />
      <mesh
        geometry={nodes.Cube043.geometry}
        material={materials.Material}
        position={[-6.547, 5.455, -6.238]}
        scale={0.901}
      />
      <mesh
        geometry={nodes.Cube044.geometry}
        material={materials.Material}
        position={[-6.45, 5.55, -6.31]}
        scale={0.901}
      />
      <mesh
        geometry={nodes.piedra1001.geometry}
        material={materials.Material}
        position={[-6.694, 0.003, 5.581]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.Material}
        position={[-6.607, 1.102, 5.524]}
      />
      <mesh
        geometry={nodes.piedra1003.geometry}
        material={materials.Material}
        position={[-6.609, 0.948, 5.52]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials.Material}
        position={[-6.664, 0.335, 5.579]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials.Material}
        position={[-6.605, 1.202, 5.53]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials.Material}
        position={[-6.642, 0.556, 5.57]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={materials.Material}
        position={[-6.639, 0.77, 5.567]}
      />
      <mesh
        geometry={nodes.Plane009.geometry}
        material={materials.Material}
        position={[-6.605, 1.448, 5.492]}
      />
      <mesh
        geometry={nodes.piedra1004.geometry}
        material={materials.Material}
        position={[-6.621, 1.532, 5.53]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={materials.Material}
        position={[-6.68, 1.679, 5.546]}
      />
      <mesh
        geometry={nodes.piedra1005.geometry}
        material={materials.Material}
        position={[-6.68, 1.896, 5.574]}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={materials.Material}
        position={[-6.726, 2.05, 5.458]}
      />
      <mesh
        geometry={nodes.Plane012.geometry}
        material={materials.Material}
        position={[-6.66, 2.266, 5.529]}
      />
      <mesh
        geometry={nodes.piedra1006.geometry}
        material={materials.Material}
        position={[-6.695, 2.683, 5.499]}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={materials.Material}
        position={[-6.687, 2.477, 5.545]}
      />
      <mesh
        geometry={nodes.Plane014.geometry}
        material={materials.Material}
        position={[-6.684, 2.848, 5.58]}
      />
      <mesh
        geometry={nodes.piedra1007.geometry}
        material={materials.Material}
        position={[-6.682, 3.055, 5.547]}
      />
      <mesh
        geometry={nodes.Plane015.geometry}
        material={materials.Material}
        position={[-6.725, 3.211, 5.597]}
      />
      <mesh
        geometry={nodes.piedra1008.geometry}
        material={materials.Material}
        position={[-6.716, 3.388, 5.591]}
      />
      <mesh
        geometry={nodes.piedra1009.geometry}
        material={materials.Material}
        position={[-6.839, 3.528, 5.644]}
      />
      <mesh
        geometry={nodes.Plane016.geometry}
        material={materials.Material}
        position={[-6.759, 4.055, 5.622]}
      />
      <mesh
        geometry={nodes.Plane017.geometry}
        material={materials.Material}
        position={[-6.807, 3.662, 5.64]}
      />
      <mesh
        geometry={nodes.piedra1010.geometry}
        material={materials.Material}
        position={[-6.797, 3.886, 5.66]}
      />
      <mesh
        geometry={nodes.piedra1011.geometry}
        material={materials.Material}
        position={[-6.896, 4.443, 5.596]}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={materials.Material}
        position={[-6.823, 4.252, 5.645]}
      />
      <mesh
        geometry={nodes.Plane019.geometry}
        material={materials.Material}
        position={[-6.936, 4.607, 5.584]}
      />
      <mesh
        geometry={nodes.Plane020.geometry}
        material={materials.Material}
        position={[-6.932, 4.757, 5.617]}
      />
      <mesh
        geometry={nodes.Plane021.geometry}
        material={materials.Material}
        position={[-6.968, 4.864, 5.625]}
      />
      <mesh
        geometry={nodes.piedra1012.geometry}
        material={materials.Material}
        position={[-6.629, 0.164, 2.763]}
      />
      <mesh
        geometry={nodes.Plane022.geometry}
        material={materials.Material}
        position={[-6.541, 1.263, 2.706]}
      />
      <mesh
        geometry={nodes.piedra1015.geometry}
        material={materials.Material}
        position={[-6.544, 1.109, 2.702]}
      />
      <mesh
        geometry={nodes.Plane023.geometry}
        material={materials.Material}
        position={[-6.599, 0.496, 2.761]}
      />
      <mesh
        geometry={nodes.Plane025.geometry}
        material={materials.Material}
        position={[-6.539, 1.363, 2.712]}
      />
      <mesh
        geometry={nodes.Plane028.geometry}
        material={materials.Material}
        position={[-6.577, 0.717, 2.752]}
      />
      <mesh
        geometry={nodes.Plane029.geometry}
        material={materials.Material}
        position={[-6.573, 0.931, 2.748]}
      />
      <mesh
        geometry={nodes.Plane030.geometry}
        material={materials.Material}
        position={[-6.54, 1.61, 2.674]}
      />
      <mesh
        geometry={nodes.piedra1016.geometry}
        material={materials.Material}
        position={[-6.556, 1.694, 2.711]}
      />
      <mesh
        geometry={nodes.Plane031.geometry}
        material={materials.Material}
        position={[-6.615, 1.84, 2.728]}
      />
      <mesh
        geometry={nodes.piedra1017.geometry}
        material={materials.Material}
        position={[-6.614, 2.057, 2.756]}
      />
      <mesh
        geometry={nodes.Plane032.geometry}
        material={materials.Material}
        position={[-6.661, 2.212, 2.64]}
      />
      <mesh
        geometry={nodes.Plane033.geometry}
        material={materials.Material}
        position={[-6.594, 2.427, 2.71]}
      />
      <mesh
        geometry={nodes.piedra1018.geometry}
        material={materials.Material}
        position={[-6.63, 2.845, 2.681]}
      />
      <mesh
        geometry={nodes.Plane034.geometry}
        material={materials.Material}
        position={[-6.621, 2.639, 2.727]}
      />
      <mesh
        geometry={nodes.Plane035.geometry}
        material={materials.Material}
        position={[-6.618, 3.009, 2.762]}
      />
      <mesh
        geometry={nodes.piedra1019.geometry}
        material={materials.Material}
        position={[-6.617, 3.216, 2.729]}
      />
      <mesh
        geometry={nodes.Plane036.geometry}
        material={materials.Material}
        position={[-6.66, 3.373, 2.779]}
      />
      <mesh
        geometry={nodes.piedra1020.geometry}
        material={materials.Material}
        position={[-6.651, 3.549, 2.773]}
      />
      <mesh
        geometry={nodes.piedra1021.geometry}
        material={materials.Material}
        position={[-6.773, 3.689, 2.826]}
      />
      <mesh
        geometry={nodes.Plane037.geometry}
        material={materials.Material}
        position={[-6.694, 4.216, 2.804]}
      />
      <mesh
        geometry={nodes.Plane038.geometry}
        material={materials.Material}
        position={[-6.767, 3.823, 2.822]}
      />
      <mesh
        geometry={nodes.piedra1022.geometry}
        material={materials.Material}
        position={[-6.731, 4.047, 2.842]}
      />
      <mesh
        geometry={nodes.piedra1023.geometry}
        material={materials.Material}
        position={[-6.831, 4.604, 2.777]}
      />
      <mesh
        geometry={nodes.Plane039.geometry}
        material={materials.Material}
        position={[-6.758, 4.414, 2.879]}
      />
      <mesh
        geometry={nodes.Plane040.geometry}
        material={materials.Material}
        position={[-6.871, 4.768, 2.765]}
      />
      <mesh
        geometry={nodes.Plane041.geometry}
        material={materials.Material}
        position={[-6.867, 4.918, 2.799]}
      />
      <mesh
        geometry={nodes.Plane042.geometry}
        material={materials.Material}
        position={[-6.836, 5.026, 2.807]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.Material}
        position={[-6.95, 5.364, 5.609]}
        rotation={[-0.164, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.Material}
        position={[-6.967, 5.562, 5.545]}
        rotation={[-0.339, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials.Material}
        position={[-6.949, 5.734, 5.477]}
        rotation={[-0.424, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials.Material}
        position={[-6.977, 5.891, 5.354]}
        rotation={[-0.665, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials.Material}
        position={[-7.008, 6.017, 5.185]}
        rotation={[-0.845, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials.Material}
        position={[-6.96, 6.115, 4.974]}
        rotation={[-1.006, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials.Material}
        position={[-6.98, 6.216, 4.77]}
        rotation={[-1.134, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials.Material}
        position={[-7.007, 6.281, 4.568]}
        rotation={[-1.307, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials.Material}
        position={[-7, 6.318, 4.376]}
        rotation={[-1.53, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials.Material}
        position={[-6.943, 6.289, 4.126]}
        rotation={[-1.654, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials.Material}
        position={[-6.922, 6.222, 3.905]}
        rotation={[-1.827, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials.Material}
        position={[-6.929, 6.169, 3.711]}
        rotation={[-1.902, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials.Material}
        position={[-6.922, 6.1, 3.477]}
        rotation={[-2.017, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials.Material}
        position={[-6.878, 5.999, 3.277]}
        rotation={[-2.152, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials.Material}
        position={[-6.826, 5.878, 3.087]}
        rotation={[-2.307, -0.008, -0.228]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials.Material}
        position={[-6.781, 5.692, 2.953]}
        rotation={[-2.461, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials.Material}
        position={[-6.797, 5.505, 2.807]}
        rotation={[-2.688, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={materials.Material}
        position={[-6.801, 5.37, 2.778]}
        rotation={[-2.688, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube045.geometry}
        material={materials.Material}
        position={[-6.839, 5.14, 5.913]}
        scale={0.468}
      />
      <mesh
        geometry={nodes.Cube046.geometry}
        material={materials.Material}
        position={[-6.833, 5.083, 6.041]}
        scale={0.468}
      />
      <mesh
        geometry={nodes.Cube047.geometry}
        material={materials.Material}
        position={[-7.28, 5.127, 5.956]}
        scale={0.468}
      />
      <mesh
        geometry={nodes.Cube048.geometry}
        material={materials.Material}
        position={[-6.801, 5.282, 2.557]}
        scale={0.901}
      />
      <mesh
        geometry={nodes.Cube049.geometry}
        material={materials.Material}
        position={[-6.745, 5.264, 2.822]}
        scale={0.901}
      />
      <mesh
        geometry={nodes.Cube050.geometry}
        material={materials.Material}
        position={[-6.945, 5.292, 2.622]}
        scale={0.901}
      />
      <mesh
        geometry={nodes.Cube051.geometry}
        material={materials.Material}
        position={[-6.848, 5.388, 2.55]}
        scale={0.901}
      />
      <mesh
        geometry={nodes.piedra1053.geometry}
        material={materials.Material}
        position={[-6.648, 0.023, 2.749]}
      />
      <mesh
        geometry={nodes.piedra1055.geometry}
        material={materials.Material}
        position={[-6.31, 0.098, -0.531]}
      />
      <mesh
        geometry={nodes.piedra1054.geometry}
        material={materials.Material}
        position={[-6.302, 0.008, -3.29]}
      />
      <mesh
        geometry={nodes.Plane043.geometry}
        material={materials.Material}
        position={[-6.225, 0.192, -6.037]}
      />
      <mesh
        geometry={nodes.Cube052.geometry}
        material={materials.Material}
        position={[-6.544, 5.411, -0.488]}
        rotation={[-0.164, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube053.geometry}
        material={materials.Material}
        position={[-6.584, 5.603, -0.52]}
        rotation={[-0.339, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube054.geometry}
        material={materials.Material}
        position={[-6.581, 5.793, -0.59]}
        rotation={[-0.424, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube055.geometry}
        material={materials.Material}
        position={[-6.648, 5.957, -0.678]}
        rotation={[-0.665, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube056.geometry}
        material={materials.Material}
        position={[-6.681, 6.083, -0.831]}
        rotation={[-0.845, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube057.geometry}
        material={materials.Material}
        position={[-6.634, 6.18, -1.042]}
        rotation={[-1.006, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube058.geometry}
        material={materials.Material}
        position={[-6.654, 6.281, -1.246]}
        rotation={[-1.134, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube059.geometry}
        material={materials.Material}
        position={[-6.681, 6.347, -1.447]}
        rotation={[-1.307, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube060.geometry}
        material={materials.Material}
        position={[-6.673, 6.384, -1.64]}
        rotation={[-1.53, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube061.geometry}
        material={materials.Material}
        position={[-6.617, 6.354, -1.89]}
        rotation={[-1.654, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube062.geometry}
        material={materials.Material}
        position={[-6.596, 6.287, -2.111]}
        rotation={[-1.827, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube063.geometry}
        material={materials.Material}
        position={[-6.602, 6.234, -2.305]}
        rotation={[-1.902, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube064.geometry}
        material={materials.Material}
        position={[-6.595, 6.166, -2.539]}
        rotation={[-2.017, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube065.geometry}
        material={materials.Material}
        position={[-6.552, 6.065, -2.739]}
        rotation={[-2.152, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Plane099.geometry}
        material={materials.Material}
        position={[-6.534, 4.919, -3.243]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials.Material}
        position={[-6.546, 5.898, -2.909]}
        rotation={[-2.346, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials.Material}
        position={[-6.525, 6.161, -3.688]}
        rotation={[-0.829, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[-6.581, 5.831, -3.252]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={materials.Material}
        position={[-6.788, 4.079, 2.139]}
        rotation={[-1.089, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials.Material}
        position={[-6.737, 4.164, 1.912]}
        rotation={[-1.099, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials.Material}
        position={[-6.728, 4.246, 1.481]}
        rotation={[-1.312, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube038.geometry}
        material={materials.Material}
        position={[-6.636, 4.24, 0.736]}
        rotation={[-1.605, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube039.geometry}
        material={materials.Material}
        position={[-6.694, 4.259, 1.241]}
        rotation={[-1.374, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube040.geometry}
        material={materials.Material}
        position={[-6.676, 4.265, 0.994]}
        rotation={[-1.462, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube066.geometry}
        material={materials.Material}
        position={[-6.323, 4.054, 0.101]}
        rotation={[-1.978, -0.013, -0.218]}
        scale={0.858}
      />
      <mesh
        geometry={nodes.Cube067.geometry}
        material={materials.Material}
        position={[-6.737, 4.192, 1.687]}
        rotation={[-1.31, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube068.geometry}
        material={materials.Material}
        position={[-6.626, 4.203, 0.578]}
        rotation={[-1.697, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube069.geometry}
        material={materials.Material}
        position={[-6.612, 4.201, 0.401]}
        rotation={[-1.697, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube070.geometry}
        material={materials.Material}
        position={[-6.504, 4.131, 0.284]}
        rotation={[-1.913, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube071.geometry}
        material={materials.Material}
        position={[-6.623, 4.027, 0.074]}
        rotation={[-1.978, -0.013, -0.218]}
        scale={0.858}
      />
      <mesh
        geometry={nodes.Cube072.geometry}
        material={materials.Material}
        position={[-6.559, 4.196, -1.065]}
        rotation={[-1.089, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube074.geometry}
        material={materials.Material}
        position={[-6.566, 4.294, -1.517]}
        rotation={[-1.312, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube075.geometry}
        material={materials.Material}
        position={[-6.497, 4.313, -2.268]}
        rotation={[-1.665, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube076.geometry}
        material={materials.Material}
        position={[-6.582, 4.332, -1.763]}
        rotation={[-1.374, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube077.geometry}
        material={materials.Material}
        position={[-6.572, 4.338, -2.01]}
        rotation={[-1.462, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube079.geometry}
        material={materials.Material}
        position={[-6.531, 4.265, -1.317]}
        rotation={[-1.31, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube080.geometry}
        material={materials.Material}
        position={[-6.53, 4.276, -2.425]}
        rotation={[-1.728, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube081.geometry}
        material={materials.Material}
        position={[-6.51, 4.204, -2.793]}
        rotation={[-1.833, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube073.geometry}
        material={materials.Material}
        position={[-6.475, 4.462, -4.083]}
        rotation={[-1.089, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube078.geometry}
        material={materials.Material}
        position={[-6.483, 4.578, -4.535]}
        rotation={[-1.312, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube082.geometry}
        material={materials.Material}
        position={[-6.378, 4.544, -5.286]}
        rotation={[-1.657, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube083.geometry}
        material={materials.Material}
        position={[-6.499, 4.616, -4.781]}
        rotation={[-1.374, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube084.geometry}
        material={materials.Material}
        position={[-6.488, 4.612, -5.028]}
        rotation={[-1.5, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube085.geometry}
        material={materials.Material}
        position={[-6.429, 4.509, -4.326]}
        rotation={[-1.31, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube086.geometry}
        material={materials.Material}
        position={[-6.404, 4.449, -5.47]}
        rotation={[-1.697, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube087.geometry}
        material={materials.Material}
        position={[-6.344, 4.281, -5.642]}
        rotation={[-1.833, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube088.geometry}
        material={materials.Material}
        position={[-6.483, 4.204, -2.638]}
        rotation={[-1.833, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube089.geometry}
        material={materials.Material}
        position={[-6.302, 1.818, -4.063]}
        rotation={[-1.089, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube090.geometry}
        material={materials.Material}
        position={[-6.31, 1.915, -4.515]}
        rotation={[-1.312, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube091.geometry}
        material={materials.Material}
        position={[-6.241, 1.935, -5.266]}
        rotation={[-1.605, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube092.geometry}
        material={materials.Material}
        position={[-6.326, 1.954, -4.761]}
        rotation={[-1.374, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube093.geometry}
        material={materials.Material}
        position={[-6.316, 1.959, -5.008]}
        rotation={[-1.501, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube094.geometry}
        material={materials.Material}
        position={[-6.274, 1.887, -4.315]}
        rotation={[-1.225, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube095.geometry}
        material={materials.Material}
        position={[-6.273, 1.897, -5.424]}
        rotation={[-1.697, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube096.geometry}
        material={materials.Material}
        position={[-6.179, 1.868, -5.621]}
        rotation={[-1.833, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube097.geometry}
        material={materials.Material}
        position={[-6.447, 4.324, -3.9]}
        rotation={[-1.008, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube098.geometry}
        material={materials.Material}
        position={[-6.366, 1.825, -1.126]}
        rotation={[-1.089, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube099.geometry}
        material={materials.Material}
        position={[-6.374, 1.922, -1.578]}
        rotation={[-1.312, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube100.geometry}
        material={materials.Material}
        position={[-6.305, 1.942, -2.329]}
        rotation={[-1.605, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube101.geometry}
        material={materials.Material}
        position={[-6.39, 1.96, -1.824]}
        rotation={[-1.374, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube102.geometry}
        material={materials.Material}
        position={[-6.38, 1.966, -2.072]}
        rotation={[-1.462, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube103.geometry}
        material={materials.Material}
        position={[-6.338, 1.894, -1.378]}
        rotation={[-1.31, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube104.geometry}
        material={materials.Material}
        position={[-6.337, 1.904, -2.487]}
        rotation={[-1.697, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube105.geometry}
        material={materials.Material}
        position={[-6.318, 1.833, -2.855]}
        rotation={[-1.833, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Cube106.geometry}
        material={materials.Material}
        position={[-6.295, 1.833, -2.699]}
        rotation={[-1.833, -0.013, -0.218]}
      />
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={materials.Material}
        position={[0.357, 0.194, -7.101]}
        scale={0.367}
      />
      <mesh
        geometry={nodes.Icosphere003.geometry}
        material={materials.Material}
        position={[0.616, 0.151, -7.056]}
        scale={-0.407}
      />
      <mesh
        geometry={nodes.Icosphere001.geometry}
        material={materials.Material}
        position={[0.457, 0.222, -7.17]}
        scale={-0.407}
      />
      <mesh
        geometry={nodes.Cube107.geometry}
        material={materials.Material}
        position={[4.03, -0.078, -5.71]}
        scale={0.659}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.Material}
        position={[3.533, -0.052, -6.196]}
        scale={0.053}
      />
      <mesh
        geometry={nodes.Cone.geometry}
        material={materials.Material}
        position={[3.559, 0.001, -6.183]}
        scale={0.009}
      />
      <mesh
        geometry={nodes.Cone001.geometry}
        material={materials.Material}
        position={[3.557, 0.001, -6.217]}
        scale={0.009}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials.Material}
        position={[3.575, -0.02, -6.194]}
        rotation={[0.08, -0.013, -0.851]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials.Material}
        position={[3.555, -0.024, -6.22]}
        rotation={[0.081, 0, -0.686]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials.Material}
        position={[3.574, -0.018, -6.21]}
        rotation={[0.079, -0.018, -0.904]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials.Material}
        position={[3.583, -0.033, -6.204]}
        rotation={[0.079, -0.018, -0.904]}
        scale={0.435}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={materials.Material}
        position={[3.533, -0.052, -6.196]}
        scale={0.053}
      />
      <mesh
        geometry={nodes.Icosphere002.geometry}
        material={materials.Material}
        position={[4.595, 0.065, -6.678]}
        scale={0.367}
      />
      <mesh
        geometry={nodes.Icosphere004.geometry}
        material={materials.Material}
        position={[4.854, 0.022, -6.633]}
        scale={-0.407}
      />
      <mesh
        geometry={nodes.Icosphere005.geometry}
        material={materials.Material}
        position={[4.695, 0.092, -6.747]}
        scale={-0.407}
      />
      <mesh
        geometry={nodes.Cube108.geometry}
        material={materials.Material}
        position={[3.533, 0.726, 6.503]}
      />
      <mesh
        geometry={nodes.Cube109.geometry}
        material={materials.Material}
        position={[5.313, 0.243, 6.464]}
      />
      <mesh
        geometry={nodes.Cube110.geometry}
        material={materials.Material}
        position={[1.742, 0.202, 6.49]}
      />
      <mesh
        geometry={nodes.Cube111.geometry}
        material={materials.Material}
        position={[3.516, 1.059, 6.977]}
        rotation={[1.832, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube112.geometry}
        material={materials.Material}
        position={[-2.406, 0.863, 6.211]}
      />
      <mesh
        geometry={nodes.Cube113.geometry}
        material={materials.Material}
        position={[-0.626, 0.38, 6.172]}
      />
      <mesh
        geometry={nodes.Cube114.geometry}
        material={materials.Material}
        position={[-4.197, 0.339, 6.198]}
      />
      <mesh
        geometry={nodes.Cube115.geometry}
        material={materials.Material}
        position={[-2.423, 1.196, 6.685]}
        rotation={[1.832, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube116.geometry}
        material={materials.Material}
        position={[3.645, 0.051, -2.564]}
        scale={0.659}
      />
      <mesh
        geometry={nodes.Sphere006.geometry}
        material={materials.Material}
        position={[3.38, 0.209, -3.158]}
        scale={0.091}
      />
      <mesh
        geometry={nodes.Sphere007.geometry}
        material={materials.Material}
        position={[3.409, 0.229, -2.917]}
        scale={-0.061}
      />
      <mesh
        geometry={nodes.Sphere008.geometry}
        material={materials.Material}
        position={[3.49, 0.24, -2.822]}
        scale={0.022}
      />
      <mesh
        geometry={nodes.Sphere009.geometry}
        material={materials.Material}
        position={[3.347, 0.237, -2.792]}
        scale={0.022}
      />
      <mesh
        geometry={nodes.Sphere010.geometry}
        material={materials.Material}
        position={[3.554, 0.216, -3.106]}
        rotation={[0.904, 0.593, 3.1]}
        scale={0.022}
      />
      <mesh
        geometry={nodes.Sphere011.geometry}
        material={materials.Material}
        position={[3.188, 0.215, -3.058]}
        rotation={[0.527, 0.325, -2.162]}
        scale={0.022}
      />
      <mesh
        geometry={nodes.Sphere012.geometry}
        material={materials.Material}
        position={[3.527, 0.146, -3.277]}
        rotation={[0.904, 0.593, 3.1]}
        scale={0.022}
      />
      <mesh
        geometry={nodes.Sphere013.geometry}
        material={materials.Material}
        position={[3.233, 0.217, -3.275]}
        rotation={[0.527, 0.325, -2.162]}
        scale={0.022}
      />
      <mesh
        geometry={nodes.Sphere014.geometry}
        material={materials.Material}
        position={[3.444, 0.327, -2.891]}
        rotation={[0.375, 0, -0.521]}
      />
      <mesh
        geometry={nodes.Sphere015.geometry}
        material={materials.Material}
        position={[3.381, 0.33, -2.885]}
        rotation={[0.375, 0, -0.521]}
      />
      <mesh
        geometry={nodes.Cube117.geometry}
        material={materials.Material}
        position={[-0.954, 0.739, 3.177]}
      />
      <mesh
        geometry={nodes.Cube118.geometry}
        material={materials.Material}
        position={[5.452, 0.262, 6.24]}
        rotation={[-Math.PI / 2, -0.529, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cube119.geometry}
        material={materials.Material}
        position={[5.348, 0.401, 6.376]}
        rotation={[-Math.PI / 2, -0.529, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cube120.geometry}
        material={materials.Material}
        position={[5.354, 0.408, 6.114]}
        rotation={[-Math.PI / 2, -0.529, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.NurbsCurve.geometry}
        material={materials.Material}
        position={[5.546, 0.008, 6.241]}
        rotation={[1.571, 0.437, -1.569]}
        scale={[0.167, 0.321, 0.624]}
      />
      <mesh
        geometry={nodes.Arbol003.geometry}
        material={materials.Material}
        position={[-2.471, 2.253, 0.039]}
        rotation={[2.445, 1.445, -2.449]}
        scale={[0.578, 0.316, 0.578]}
      />
    </group>
  )
}

useGLTF.preload("/Isla.glb")
